export interface EventData {
  id: string;
  title: string;
  description?: string;
  imageUrl?: string;
  sourceUrl: string;
  startDate: string;
  endDate: string;
  time?: string;
  placeName: string;
  address?: string;
  district: string;
  category: string;
  vibes: string[];
  source: string;
  score: number;
  price?: string;
  outdoor: boolean;
  coordsX?: number;
  coordsY?: number;
  going?: number;
  friendsGoing?: number;
  friendsAvatars?: string[];
}

export const districts = [
  { value: "StareMiasto", label: "Stare Miasto" },
  { value: "Jezyce", label: "Jeżyce" },
  { value: "Lazarz", label: "Łazarz" },
  { value: "Grunwald", label: "Grunwald" },
  { value: "Wilda", label: "Wilda" },
  { value: "Rataje", label: "Rataje" },
  { value: "Piatkowo", label: "Piątkowo" },
  { value: "Winogrady", label: "Winogrady" },
  { value: "NoweMiasto", label: "Nowe Miasto" },
  { value: "Inny", label: "Inny" },
];

export const categories = [
  { value: "Kino", label: "Kino" },
  { value: "Sztuka", label: "Sztuka" },
  { value: "Muzyka", label: "Muzyka" },
  { value: "Sport", label: "Sport" },
  { value: "Teatr", label: "Teatr" },
  { value: "Warsztaty", label: "Warsztaty" },
  { value: "Konferencje", label: "Konferencje" },
  { value: "Jedzenie", label: "Jedzenie" },
  { value: "Inne", label: "Inne" },
];

export const vibes = [
  { value: "Randka", label: "Randka" },
  { value: "Impreza", label: "Impreza" },
  { value: "WyjscieZeZnajomymi", label: "Wyjście ze znajomymi" },
  { value: "Rodzinne", label: "Rodzinne" },
  { value: "Spokojne", label: "Spokojne" },
  { value: "Kulturalne", label: "Kulturalne" },
  { value: "Aktywne", label: "Aktywne" },
];

export const vibeEmoji: Record<string, string> = {
  Randka: "💕",
  Impreza: "🥳",
  WyjscieZeZnajomymi: "👥",
  Rodzinne: "🧸",
  Spokojne: "🌙",
  Kulturalne: "🎭",
  Aktywne: "⚡",
};

export const categoryEmoji: Record<string, string> = {
  Kino: "🎬",
  Sztuka: "🎨",
  Muzyka: "🎵",
  Sport: "⚡",
  Teatr: "🎭",
  Warsztaty: "🔧",
  Konferencje: "💼",
  Jedzenie: "🍕",
  Inne: "📌",
};

export const categoryColors: Record<string, { bg: string; fg: string }> = {
  Muzyka: { bg: "#FF3D7F", fg: "#4A0B23" },
  Kino: { bg: "#6E3DFF", fg: "#1F0A55" },
  Sztuka: { bg: "#2860FF", fg: "#07194C" },
  Sport: { bg: "#C8FF2E", fg: "#1F2A04" },
  Teatr: { bg: "#FF6B2C", fg: "#4A1A02" },
  Warsztaty: { bg: "#E89A6B", fg: "#3A1C0A" },
  Konferencje: { bg: "#1F2D5A", fg: "#F4F4FB" },
  Jedzenie: { bg: "#FFB627", fg: "#3A2200" },
  Inne: { bg: "#E8E3D8", fg: "#1A1A1A" },
};

const today = new Date();

export const MOCK_EVENTS: EventData[] = [
  {
    id: "e1",
    title: "Kortez — solo akustycznie",
    description: "Kortez w kameralnej odsłonie solo acoustic. Bilety dostępne online.",
    imageUrl: "https://picsum.photos/seed/kortez/600/400",
    sourceUrl: "https://pik.poznan.pl/kortez-koncert-poznan",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 20, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 22, 0).toISOString(),
    time: "20:00",
    placeName: "CK Zamek",
    address: "Św. Marcin 80/82",
    district: "StareMiasto",
    category: "Muzyka",
    vibes: ["Randka", "Spokojne"],
    source: "pikpoznan",
    score: 94,
    price: "79 zł",
    outdoor: false,
    coordsX: 52.4083, coordsY: 16.9192,
    going: 412,
    friendsGoing: 3,
    friendsAvatars: ["A", "K", "M"],
  },
  {
    id: "e2",
    title: "Seans: Strefa interesów",
    description: "Pokaz nagrodzonego Oscarami filmu w Kinie Muza.",
    imageUrl: "https://picsum.photos/seed/strefa/600/400",
    sourceUrl: "https://pik.poznan.pl/seans-strefa",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 18, 30).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 20, 30).toISOString(),
    time: "18:30",
    placeName: "Kino Muza",
    address: "Święty Marcin 30",
    district: "StareMiasto",
    category: "Kino",
    vibes: ["Randka", "Kulturalne"],
    source: "pikpoznan",
    score: 88,
    price: "32 zł",
    outdoor: false,
    coordsX: 52.4063, coordsY: 16.9205,
    going: 156,
    friendsAvatars: ["T"],
  },
  {
    id: "e3",
    title: "Balonowe Show — widowisko dla dzieci",
    description: "Teatralne widowisko balonowe dla najmłodszych.",
    imageUrl: "https://picsum.photos/seed/balonowe/600/400",
    sourceUrl: "https://pik.poznan.pl/balonowe-show",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2, 12, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2, 14, 0).toISOString(),
    time: "12:00",
    placeName: "Teatr Animacji",
    address: "Św. Marcin 80/82",
    district: "StareMiasto",
    category: "Teatr",
    vibes: ["Rodzinne"],
    source: "pikpoznan",
    score: 76,
    price: "45 zł",
    outdoor: false,
    coordsX: 52.4075, coordsY: 16.9180,
    going: 89,
  },
  {
    id: "e4",
    title: "Warsztaty kulinarne: Kuchnia włoska",
    description: "Naucz się robić prawdziwą pizzę i makaron od włoskiego szefa.",
    imageUrl: "https://picsum.photos/seed/kuchnia/600/400",
    sourceUrl: "https://pik.poznan.pl/warsztaty-wloska",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 17, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 3, 20, 0).toISOString(),
    time: "17:00",
    placeName: "Szkoła Gotowania Kucharz",
    address: "Głogowska 45",
    district: "Lazarz",
    category: "Jedzenie",
    vibes: ["WyjscieZeZnajomymi", "Impreza"],
    source: "pikpoznan",
    score: 72,
    price: "120 zł",
    outdoor: false,
    coordsX: 52.3935, coordsY: 16.8940,
    going: 45,
    friendsGoing: 2,
    friendsAvatars: ["P", "J"],
  },
  {
    id: "e5",
    title: "Poznański Bieg Uliczny",
    description: "Bieg na 10 km przez centrum Poznania. Trasa przez Maltę i Śródkę.",
    imageUrl: "https://picsum.photos/seed/bieg/600/400",
    sourceUrl: "https://pik.poznan.pl/bieg-poznan",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 4, 9, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 4, 12, 0).toISOString(),
    time: "09:00",
    placeName: "Maltanka",
    address: "Wiankowa 2",
    district: "NoweMiasto",
    category: "Sport",
    vibes: ["Aktywne"],
    source: "pikpoznan",
    score: 65,
    price: "35 zł",
    outdoor: true,
    coordsX: 52.4015, coordsY: 16.9560,
    going: 234,
    friendsGoing: 1,
    friendsAvatars: ["E"],
  },
  {
    id: "e6",
    title: "Nocne zwiedzanie Starego Miasta",
    description: "Spacer z przewodnikiem po nocnym Starym Rynku.",
    imageUrl: "https://picsum.photos/seed/nocne/600/400",
    sourceUrl: "https://pik.poznan.pl/nocne-zwiedzanie",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 5, 22, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 5, 23, 30).toISOString(),
    time: "22:00",
    placeName: "Stary Rynek",
    address: "Stary Rynek",
    district: "StareMiasto",
    category: "Inne",
    vibes: ["WyjscieZeZnajomymi", "Impreza"],
    source: "pikpoznan",
    score: 58,
    price: "25 zł",
    outdoor: true,
    coordsX: 52.4085, coordsY: 16.9340,
    going: 167,
    friendsGoing: 5,
    friendsAvatars: ["M", "K", "A"],
  },
  {
    id: "e7",
    title: "Mela Koteluk — koncert",
    description: "Koncert w klimatycznej Sali Ziemi.",
    imageUrl: "https://picsum.photos/seed/mela/600/400",
    sourceUrl: "https://pik.poznan.pl/mela-koteluk",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 6, 20, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 6, 22, 30).toISOString(),
    time: "20:00",
    placeName: "Sala Ziemi",
    address: "Głogowska 14",
    district: "Grunwald",
    category: "Muzyka",
    vibes: ["Randka", "Kulturalne"],
    source: "pikpoznan",
    score: 82,
    price: "89 zł",
    outdoor: false,
    coordsX: 52.3960, coordsY: 16.9000,
    going: 298,
    friendsAvatars: ["W"],
  },
  {
    id: "e8",
    title: "Joga w Parku Cytadela",
    description: "Poranna joga na świeżym powietrzu. Dla początkujących.",
    imageUrl: "https://picsum.photos/seed/joga/600/400",
    sourceUrl: "https://pik.poznan.pl/joga-cytadela",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7, 8, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7, 9, 30).toISOString(),
    time: "08:00",
    placeName: "Park Cytadela",
    address: "Aleja Armii Poznań",
    district: "Winogrady",
    category: "Sport",
    vibes: ["Spokojne"],
    source: "pikpoznan",
    score: 45,
    price: "0 zł",
    outdoor: true,
    coordsX: 52.4200, coordsY: 16.9380,
    going: 67,
  },
  {
    id: "e9",
    title: "Wernisaż: Malarstwo Wielkiego Formatu",
    description: "Wystawa prac młodych artystów z Poznania.",
    imageUrl: "https://picsum.photos/seed/wernisaz/600/400",
    sourceUrl: "https://pik.poznan.pl/wernisaz",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 8, 18, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 30, 20, 0).toISOString(),
    time: "18:00",
    placeName: "Galeria Miejska Arsenał",
    address: "Stary Rynek 6",
    district: "StareMiasto",
    category: "Sztuka",
    vibes: ["Kulturalne", "Spokojne"],
    source: "pikpoznan",
    score: 40,
    price: "0 zł",
    outdoor: false,
    coordsX: 52.4070, coordsY: 16.9345,
    going: 34,
  },
  {
    id: "e10",
    title: "Konferencja: Poznań Tech Summit",
    description: "Największa konferencja technologiczna w Wielkopolsce.",
    imageUrl: "https://picsum.photos/seed/techsummit/600/400",
    sourceUrl: "https://pik.poznan.pl/tech-summit",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 14, 9, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15, 18, 0).toISOString(),
    time: "09:00",
    placeName: "MTP",
    address: "Głogowska 14",
    district: "Grunwald",
    category: "Konferencje",
    vibes: ["Aktywne", "WyjscieZeZnajomymi"],
    source: "pikpoznan",
    score: 55,
    price: "249 zł",
    outdoor: false,
    coordsX: 52.3965, coordsY: 16.8990,
    going: 523,
    friendsGoing: 4,
    friendsAvatars: ["R", "T", "X"],
  },
  {
    id: "e11",
    title: "Festiwal Sztuki Współczesnej",
    description: "Trzydniowy festiwal w Starym Browarze.",
    imageUrl: "https://picsum.photos/seed/sztuka-festiwal/600/400",
    sourceUrl: "https://pik.poznan.pl/festiwal-sztuki",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 10, 10, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 12, 20, 0).toISOString(),
    time: "10:00",
    placeName: "Stary Browar",
    address: "Półwiejska 42",
    district: "StareMiasto",
    category: "Sztuka",
    vibes: ["Kulturalne"],
    source: "pikpoznan",
    score: 68,
    price: "55 zł",
    outdoor: false,
    coordsX: 52.4030, coordsY: 16.9260,
    going: 189,
    friendsAvatars: ["A", "K"],
  },
  {
    id: "e12",
    title: "Impreza: Lata 80 & 90 Disco Party",
    description: "Powrót do przeszłości — najlepsze hity lat 80 i 90.",
    imageUrl: "https://picsum.photos/seed/disco/600/400",
    sourceUrl: "https://pik.poznan.pl/disco-party",
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1, 22, 0).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2, 3, 0).toISOString(),
    time: "22:00",
    placeName: "Cuba Libre",
    address: "Wrocławska 21",
    district: "StareMiasto",
    category: "Muzyka",
    vibes: ["Impreza", "WyjscieZeZnajomymi"],
    source: "pikpoznan",
    score: 91,
    price: "35 zł",
    outdoor: false,
    coordsX: 52.4050, coordsY: 16.9350,
    going: 876,
    friendsGoing: 8,
    friendsAvatars: ["Z", "Y", "X", "W"],
  },
];
