export { districts, categories, vibes, vibeEmoji, categoryColors, categoryEmoji } from "./data";

export const preferenceLabels: Record<string, string> = {
  StareMiasto: "Stare Miasto",
  Jezyce: "Jeżyce",
  Lazarz: "Łazarz",
  Grunwald: "Grunwald",
  Wilda: "Wilda",
  Rataje: "Rataje",
  Piatkowo: "Piątkowo",
  Winogrady: "Winogrady",
  NoweMiasto: "Nowe Miasto",
  Inny: "Inny",
  Kino: "Kino",
  Sztuka: "Sztuka",
  Muzyka: "Muzyka",
  Sport: "Sport",
  Teatr: "Teatr",
  Warsztaty: "Warsztaty",
  Konferencje: "Konferencje",
  Jedzenie: "Jedzenie",
  Inne: "Inne",
  Randka: "Randka",
  Impreza: "Impreza",
  WyjscieZeZnajomymi: "Wyjście ze znajomymi",
  Rodzinne: "Rodzinne",
  Spokojne: "Spokojne",
  Kulturalne: "Kulturalne",
  Aktywne: "Aktywne",
};
