export const VENUES: Record<string, { address: string; district: string; lat: number; lon: number }> = {
  "CK Zamek": { address: "Święty Marcin 80/82", district: "Centrum", lat: 52.408, lon: 16.919 },
  "Stary Browar": { address: "Półwiejska 42", district: "StareMiasto", lat: 52.403, lon: 16.926 },
  "Kino Muza": { address: "Święty Marcin 30", district: "Centrum", lat: 52.406, lon: 16.920 },
  "Teatr Polski": { address: "27 Grudnia 8/10", district: "StareMiasto", lat: 52.407, lon: 16.935 },
  "Teatr Nowy": { address: "Dąbrowskiego 5", district: "Centrum", lat: 52.407, lon: 16.930 },
  "Teatr Wielki": { address: "Fredry 9", district: "Centrum", lat: 52.409, lon: 16.928 },
  "Teatr Animacji": { address: "Św. Marcin 80/82", district: "Centrum", lat: 52.407, lon: 16.918 },
  "Polski Teatr Tańca": { address: "Taczaka 8", district: "Centrum", lat: 52.405, lon: 16.925 },
  "Blue Note": { address: "Kościuszki 79", district: "Jezyce", lat: 52.413, lon: 16.900 },
  "Klub B17": { address: "Bułgarska 17", district: "Jezyce", lat: 52.418, lon: 16.895 },
  "Klub Pod Minogą": { address: "Nowowiejskiego 8", district: "Jezyce", lat: 52.415, lon: 16.898 },
  "Tama": { address: "Niepodległości 12", district: "Jezyce", lat: 52.410, lon: 16.895 },
  "2progi": { address: "Kutrzeby 6", district: "Jezyce", lat: 52.414, lon: 16.892 },
  "MTP": { address: "Głogowska 14", district: "Grunwald", lat: 52.396, lon: 16.898 },
  "Sala Ziemi": { address: "Głogowska 14", district: "Grunwald", lat: 52.396, lon: 16.899 },
  "Aula UAM": { address: "Wieniawskiego 1", district: "Centrum", lat: 52.406, lon: 16.927 },
  "Aula Artis": { address: "Święty Marcin 40", district: "Centrum", lat: 52.407, lon: 16.922 },
  "Aula Nova": { address: "Święty Marcin 40", district: "Centrum", lat: 52.407, lon: 16.923 },
  "Cuba Libre": { address: "Wrocławska 21", district: "StareMiasto", lat: 52.405, lon: 16.935 },
  "Galeria Miejska Arsenał": { address: "Stary Rynek 6", district: "Centrum", lat: 52.407, lon: 16.934 },
  "Galeria Ego": { address: "Wyspiańskiego 41", district: "Centrum", lat: 52.404, lon: 16.928 },
  "Collegium Da Vinci": { address: "Kutrzeby 10", district: "Grunwald", lat: 52.397, lon: 16.895 },
  "CK Zamek - Sala Wielka": { address: "Święty Marcin 80/82", district: "Centrum", lat: 52.408, lon: 16.919 },
  "Scena Wspólna": { address: "Brandstaettera 1", district: "StareMiasto", lat: 52.425, lon: 16.940 },
  "Scena na Piętrze": { address: "Masztalarska 8", district: "StareMiasto", lat: 52.408, lon: 16.933 },
  "Teatr Ósmego Dnia": { address: "Ratajczaka 44", district: "StareMiasto", lat: 52.403, lon: 16.921 },
  "Park Cytadela": { address: "Aleja Armii Poznań", district: "StareMiasto", lat: 52.430, lon: 16.938 },
  "Scena nad Rusałką": { address: "Rusałka", district: "StareMiasto", lat: 52.432, lon: 16.928 },
  "Klub Dragon": { address: "Zamkowa 3", district: "StareMiasto", lat: 52.409, lon: 16.930 },
  "Zamek Cesarski": { address: "Św. Marcin 80/82", district: "Centrum", lat: 52.408, lon: 16.922 },
  "POSiR Rataje": { address: "Piłsudskiego 30", district: "NoweMiasto", lat: 52.380, lon: 16.963 },
  "POSiR Malta": { address: "Wiankowa 2", district: "NoweMiasto", lat: 52.401, lon: 16.960 },
  "Jezioro Strzeszyńskie": { address: "Kosowska", district: "Jezyce", lat: 52.444, lon: 16.842 },
  "Enea Stadion": { address: "Bułgarska 17", district: "Jezyce", lat: 52.398, lon: 16.858 },
  "Kino Apollo": { address: "Ratajczaka 18", district: "Centrum", lat: 52.405, lon: 16.927 },
  "Port Lotniczy Poznań Ławica": { address: "Bukowska 285", district: "Grunwald", lat: 52.415, lon: 16.829 },
  "Malta": { address: "Malta", district: "NoweMiasto", lat: 52.401, lon: 16.960 },
  "Termy Maltańskie": { address: "Termalna 1", district: "NoweMiasto", lat: 52.394, lon: 16.969 },
  "Arena": { address: "Wyspiańskiego 33", district: "Jezyce", lat: 52.406, lon: 16.895 },
  "Stary Rynek": { address: "Stary Rynek", district: "Centrum", lat: 52.408, lon: 16.934 },
  "Rynek Łazarski": { address: "Rynek Łazarski", district: "Grunwald", lat: 52.393, lon: 16.901 },
  "Plac Wolności": { address: "Plac Wolności", district: "Centrum", lat: 52.408, lon: 16.928 },
  "Ostrów Tumski": { address: "Ostrów Tumski", district: "NoweMiasto", lat: 52.411, lon: 16.949 },
  "Barak Kultury": { address: "Św. Marcin 75", district: "Centrum", lat: 52.408, lon: 16.918 },
  "Filharmonia Poznańska": { address: "Św. Marcin 81", district: "Centrum", lat: 52.408, lon: 16.918 },
  "Pawilon": { address: "Ewangelicka 1", district: "StareMiasto", lat: 52.406, lon: 16.940 },
  "Meskalina": { address: "Stary Rynek 6", district: "Centrum", lat: 52.407, lon: 16.934 },
  "Dom Tramwajarza": { address: "Słowackiego 19/21", district: "Jezyce", lat: 52.415, lon: 16.891 },
  "Scena Robocza": { address: "Grunwaldzka 55", district: "Grunwald", lat: 52.398, lon: 16.892 },
  "KontenerART": { address: "Ewangelicka", district: "StareMiasto", lat: 52.405, lon: 16.941 },
  "Nocny Targ Towarzyski": { address: "Kolejowa 23", district: "Jezyce", lat: 52.409, lon: 16.896 },
  "Targowa": { address: "Polska 11", district: "StareMiasto", lat: 52.404, lon: 16.932 },
  "SARP": { address: "Stary Rynek 56", district: "Centrum", lat: 52.408, lon: 16.933 },
  "Bałtyk": { address: "Roosevelta 22", district: "Jezyce", lat: 52.411, lon: 16.901 },
  "Zenit": { address: "Głogowska 108b", district: "Grunwald", lat: 52.388, lon: 16.887 },
  "Kino Rialto": { address: "Dąbrowskiego 38", district: "Jezyce", lat: 52.414, lon: 16.904 },
  "Kino Pałacowe": { address: "Św. Marcin 80/82", district: "Centrum", lat: 52.408, lon: 16.919 },
  "Przystanek Pireus": { address: "Głogowska 18", district: "Grunwald", lat: 52.397, lon: 16.898 },
  "Pub Pod Kominem": { address: "Woźna 11", district: "Centrum", lat: 52.406, lon: 16.936 },
  "Ministerstwo Browaru": { address: "Wroniecka 16", district: "Centrum", lat: 52.409, lon: 16.936 },
  "Rozbrat": { address: "Pułaskiego 21b", district: "Jezyce", lat: 52.410, lon: 16.893 },
  "Mięsna": { address: "Półwiejska 20", district: "StareMiasto", lat: 52.402, lon: 16.930 },
  "Kisielice": { address: "Taczaka 25", district: "Centrum", lat: 52.404, lon: 16.923 },
  "Bulwar": { address: "Księcia Józefa 9", district: "NoweMiasto", lat: 52.411, lon: 16.945 },
  "Dom Kultury Kolejarza": { address: "Głogowska 90", district: "Grunwald", lat: 52.393, lon: 16.892 },
  "Uniwersytet Artystyczny": { address: "Al. Marcinkowskiego 29", district: "Centrum", lat: 52.406, lon: 16.929 },
  "Politechnika Poznańska": { address: "Piotrowo 3", district: "NoweMiasto", lat: 52.395, lon: 16.955 },
  "Uniwersytet Ekonomiczny": { address: "Al. Niepodległości 10", district: "Centrum", lat: 52.405, lon: 16.923 },
  "Uniwersytet Medyczny": { address: "Fredry 10", district: "Centrum", lat: 52.410, lon: 16.928 },
  "Uniwersytet Przyrodniczy": { address: "Wojska Polskiego 28", district: "Jezyce", lat: 52.412, lon: 16.898 },
  "Muzeum Narodowe": { address: "Al. Marcinkowskiego 9", district: "Centrum", lat: 52.408, lon: 16.930 },
  "Brama Poznania": { address: "Gdańska 2", district: "NoweMiasto", lat: 52.412, lon: 16.948 },
  "Rogalowe Muzeum": { address: "Stary Rynek 41", district: "Centrum", lat: 52.407, lon: 16.934 },
  "Katedra Poznańska": { address: "Ostrów Tumski 17", district: "NoweMiasto", lat: 52.411, lon: 16.949 },
  "Fara Poznańska": { address: "Gołębia 1", district: "Centrum", lat: 52.407, lon: 16.934 },
  "Kościół św. Wojciecha": { address: "Wzgórze św. Wojciecha 1", district: "StareMiasto", lat: 52.410, lon: 16.937 },
  "Park Sołacki": { address: "Park Sołacki", district: "Jezyce", lat: 52.420, lon: 16.888 },
  "Park Wilsona": { address: "Park Wilsona", district: "Grunwald", lat: 52.397, lon: 16.908 },
  "Park Kasprowicza": { address: "Park Kasprowicza", district: "Jezyce", lat: 52.411, lon: 16.895 },
  "Tor Regatowy Malta": { address: "Wiankowa 2", district: "NoweMiasto", lat: 52.402, lon: 16.961 },
  "Tor Poznań": { address: "Wyścigowa 3", district: "Grunwald", lat: 52.387, lon: 16.894 },
  "Pływalnia Rataje": { address: "Piłsudskiego 30", district: "NoweMiasto", lat: 52.381, lon: 16.963 },
  "AZS Poznań": { address: "Noskowskiego 6a", district: "Wilda", lat: 52.393, lon: 16.919 },
  "MTP Pawilon 3": { address: "Głogowska 14", district: "Grunwald", lat: 52.396, lon: 16.899 },
  "MTP Pawilon 3a": { address: "Głogowska 14", district: "Grunwald", lat: 52.396, lon: 16.900 },
  "MTP Pawilon 5": { address: "Głogowska 14", district: "Grunwald", lat: 52.397, lon: 16.900 },
  "MTP Pawilon 15": { address: "Głogowska 14", district: "Grunwald", lat: 52.395, lon: 16.898 },
  "Teatr Muzyczny": { address: "Niezłomnych 1e", district: "Wilda", lat: 52.390, lon: 16.922 },
  "Teatr Cortiqué": { address: "Mickiewicza 7", district: "Centrum", lat: 52.409, lon: 16.926 },
  "Scena UAP": { address: "Al. Marcinkowskiego 29", district: "Centrum", lat: 52.406, lon: 16.929 },
  "CK Zamek Scena Nowa": { address: "Św. Marcin 80/82", district: "Centrum", lat: 52.408, lon: 16.919 },
  "Galeria Skala": { address: "Grunwaldzka 7", district: "Grunwald", lat: 52.400, lon: 16.897 },
  "Klub Muzyczny Łazienki": { address: "Głogowska 34", district: "Grunwald", lat: 52.393, lon: 16.896 },
  "Dom Studencki Jowita": { address: "Zwierzyniecka 7", district: "Centrum", lat: 52.405, lon: 16.922 },
  "Hotel Bazar": { address: "Al. Marcinkowskiego 10", district: "Centrum", lat: 52.408, lon: 16.930 },
  "Hotel Mercure": { address: "Roosevelta 20", district: "Jezyce", lat: 52.411, lon: 16.901 },
  "Hotel Sheraton": { address: "Bukowska 3/9", district: "Jezyce", lat: 52.408, lon: 16.900 },
  "Hotel Novotel": { address: "pl. Andersa 1", district: "StareMiasto", lat: 52.410, lon: 16.937 },
  "Hotel Vivaldi": { address: "Winogrady 100", district: "StareMiasto", lat: 52.419, lon: 16.920 },
  "Hotel City Park": { address: "Wyspiańskiego 26a", district: "Centrum", lat: 52.405, lon: 16.906 },
  "Sala Koncertowa AM": { address: "Św. Marcin 87", district: "Centrum", lat: 52.408, lon: 16.917 },
  "Ogród Botaniczny UAM": { address: "Dąbrowskiego 165", district: "Jezyce", lat: 52.425, lon: 16.880 },
  "Palmiarnia Poznańska": { address: "Matejki 18", district: "Jezyce", lat: 52.410, lon: 16.910 },
  "Nowe Zoo": { address: "Krańcowa 81", district: "NoweMiasto", lat: 52.399, lon: 16.991 },
  "Stare Zoo": { address: "Zwierzyniecka 19", district: "Centrum", lat: 52.408, lon: 16.909 },
  "Muzeum Archeologiczne": { address: "Wodna 27", district: "Centrum", lat: 52.406, lon: 16.936 },
  "Muzeum Etnograficzne": { address: "Grobla 25", district: "Centrum", lat: 52.404, lon: 16.936 },
  "Kamienica MTP": { address: "Bukowska 14", district: "Grunwald", lat: 52.399, lon: 16.899 },
};

// Keywords → venue fallback for when venue name doesn't appear verbatim
const KEYWORD_VENUES: [string, string][] = [
  ["zamek", "CK Zamek"],
  ["stary browar", "Stary Browar"],
  ["muza", "Kino Muza"],
  ["teatr polski", "Teatr Polski"],
  ["teatr nowy", "Teatr Nowy"],
  ["teatr wielki", "Teatr Wielki"],
  ["teatr animacji", "Teatr Animacji"],
  ["blue note", "Blue Note"],
  ["klub b17", "Klub B17"],
  ["pod minogą", "Klub Pod Minogą"],
  ["mtp", "MTP"],
  ["sala ziemi", "Sala Ziemi"],
  ["aula uam", "Aula UAM"],
  ["aulą uam", "Aula UAM"],
  ["aula artis", "Aula Artis"],
  ["cuba libre", "Cuba Libre"],
  ["galeria miejska", "Galeria Miejska Arsenał"],
  ["arsenał", "Galeria Miejska Arsenał"],
  ["galeria ego", "Galeria Ego"],
  ["stary rynek", "Stary Rynek"],
  ["rynek łazarski", "Rynek Łazarski"],
  ["plac wolności", "Plac Wolności"],
  ["ostrów tumski", "Ostrów Tumski"],
  ["cytadela", "Park Cytadela"],
  ["malta", "Malta"],
  ["termy", "Termy Maltańskie"],
  ["stadion", "Enea Stadion"],
  ["arena", "Arena"],
  ["rusałka", "Scena nad Rusałką"],
  ["barak kultury", "Barak Kultury"],
  ["browar", "Stary Browar"],
  ["kino muza", "Kino Muza"],
  ["teatr animacji", "Teatr Animacji"],
  // JSON-LD name variants from pikpoznan.pl
  ["klub blue note", "Blue Note"],
  ["blue note poznań", "Blue Note"],
  ["klub b17", "Klub B17"],
  ["ck zamek poznań", "CK Zamek"],
  ["centrum kultury zamek", "CK Zamek"],
  ["zamek poznań", "CK Zamek"],
  ["kino muza poznań", "Kino Muza"],
  ["teatr polski poznań", "Teatr Polski"],
  ["teatr nowy poznań", "Teatr Nowy"],
  ["teatr wielki poznań", "Teatr Wielki"],
  ["aula uam poznań", "Aula UAM"],
  ["uniwersytet im. adama mickiewicza", "Aula UAM"],
  ["mtp poznań", "MTP"],
  ["międzynarodowe targi poznańskie", "MTP"],
  ["sala ziemi poznań", "Sala Ziemi"],
  ["stary browar poznań", "Stary Browar"],
  ["galeria malta", "Malta"],
  ["termy maltańskie", "Termy Maltańskie"],
  ["stadion poznań", "Enea Stadion"],
  ["stadion miejski", "Enea Stadion"],
  ["collegium da vinci", "Collegium Da Vinci"],
  ["klub b17", "Klub B17"],
  ["letnia strefa", "Klub B17"],
  ["klub pod minogą", "Klub Pod Minogą"],
  ["blue note poznań", "Blue Note"],
  ["port lotniczy", "Port Lotniczy Poznań Ławica"],
  ["port ławica", "Port Lotniczy Poznań Ławica"],
  ["ławica", "Port Lotniczy Poznań Ławica"],
  ["lotnisko", "Port Lotniczy Poznań Ławica"],
  ["enea", "Enea Stadion"],
  ["stadion główny", "Enea Stadion"],
  ["kino apollo", "Kino Apollo"],
  ["apollo", "Kino Apollo"],
  ["filharmonia", "Filharmonia Poznańska"],
  ["pawilon", "Pawilon"],
  ["meskalina", "Meskalina"],
  ["dom tramwajarza", "Dom Tramwajarza"],
  ["tramwajarz", "Dom Tramwajarza"],
  ["scena robocza", "Scena Robocza"],
  ["kontenerart", "KontenerART"],
  ["nocny targ towarzyski", "Nocny Targ Towarzyski"],
  ["nocny targ", "Nocny Targ Towarzyski"],
  ["targowa", "Targowa"],
  ["sarp", "SARP"],
  ["bałtyk", "Bałtyk"],
  ["zenit", "Zenit"],
  ["kino rialto", "Kino Rialto"],
  ["rialto", "Kino Rialto"],
  ["kino pałacowe", "Kino Pałacowe"],
  ["przystanek pireus", "Przystanek Pireus"],
  ["pireus", "Przystanek Pireus"],
  ["pod kominem", "Pub Pod Kominem"],
  ["ministerstwo browaru", "Ministerstwo Browaru"],
  ["rozbrat", "Rozbrat"],
  ["mięsna", "Mięsna"],
  ["kisielice", "Kisielice"],
  ["bulwar", "Bulwar"],
  ["dom kultury kolej", "Dom Kultury Kolejarza"],
  ["uniwersytet artystyczny", "Uniwersytet Artystyczny"],
  ["politechnika poznańska", "Politechnika Poznańska"],
  ["politechniki poznańskiej", "Politechnika Poznańska"],
  ["uniwersytet ekonomiczny", "Uniwersytet Ekonomiczny"],
  ["uniwersytetu ekonomicznego", "Uniwersytet Ekonomiczny"],
  ["uniwersytet medyczny", "Uniwersytet Medyczny"],
  ["uniwersytetu medycznego", "Uniwersytet Medyczny"],
  ["uniwersytet przyrodniczy", "Uniwersytet Przyrodniczy"],
  ["uniwersytetu przyrodniczego", "Uniwersytet Przyrodniczy"],
  ["muzeum narodowe", "Muzeum Narodowe"],
  ["muzeum narodowego", "Muzeum Narodowe"],
  ["brama poznania", "Brama Poznania"],
  ["rogalowe muzeum", "Rogalowe Muzeum"],
  ["targi śniadaniowe", "Targowa"],
  ["katedra poznańska", "Katedra Poznańska"],
  ["fara poznańska", "Fara Poznańska"],
  ["fara", "Fara Poznańska"],
  ["kościół św. wojciecha", "Kościół św. Wojciecha"],
  ["park sołacki", "Park Sołacki"],
  ["park wilsona", "Park Wilsona"],
  ["park kasprowicza", "Park Kasprowicza"],
  ["tor regatowy", "Tor Regatowy Malta"],
  ["tor poznań", "Tor Poznań"],
  ["pływalnia rataje", "Pływalnia Rataje"],
  ["azs", "AZS Poznań"],
  ["teatr muzyczny", "Teatr Muzyczny"],
  ["teatru muzycznego", "Teatr Muzyczny"],
  ["cortiqué", "Teatr Cortiqué"],
  ["scena uap", "Scena UAP"],
  ["galeria skala", "Galeria Skala"],
  ["klub łazienki", "Klub Muzyczny Łazienki"],
  ["jowita", "Dom Studencki Jowita"],
  ["dom studencki", "Dom Studencki Jowita"],
  ["hotel bazar", "Hotel Bazar"],
  ["hotel mercure", "Hotel Mercure"],
  ["hotel sheraton", "Hotel Sheraton"],
  ["sheraton", "Hotel Sheraton"],
  ["hotel novotel", "Hotel Novotel"],
  ["novotel", "Hotel Novotel"],
  ["hotel vivaldi", "Hotel Vivaldi"],
  ["hotel city park", "Hotel City Park"],
  ["sala koncertowa am", "Sala Koncertowa AM"],
  ["akademia muzyczna", "Sala Koncertowa AM"],
  ["ogród botaniczny", "Ogród Botaniczny UAM"],
  ["palmiarnia", "Palmiarnia Poznańska"],
  ["nowe zoo", "Nowe Zoo"],
  ["stare zoo", "Stare Zoo"],
  ["muzeum archeologiczne", "Muzeum Archeologiczne"],
  ["muzeum etnograficzne", "Muzeum Etnograficzne"],
  ["kamienica mtp", "Kamienica MTP"],
  ["teatr animacji", "Teatr Animacji"],
];

export function matchVenue(text: string): { address: string; district: string; lat: number; lon: number } | null {
  const lower = text.toLowerCase();

  // First try exact venue name match
  for (const [name, data] of Object.entries(VENUES)) {
    if (lower.includes(name.toLowerCase())) {
      return data;
    }
  }

  // Then try keyword match
  for (const [keyword, venueName] of KEYWORD_VENUES) {
    if (lower.includes(keyword)) {
      return VENUES[venueName] ?? null;
    }
  }

  return null;
}
